Add TP1 + structure
sebclrsn/TP-AOO-python-git pull request #1
Opened 2024-02-29 13:49 UTC by LoicRiegel

Dis-moi si ca te parait OK :)
Je leur enverrai l'API key par mail avant la séance, mais je peux pas l'uploader ici, d'autant plus que c'est publique ^^

2024-02-29 16:49 UTC, sebclrsn requested changes

2024-02-29 16:49 UTC, sebclrsn commented on TP1/README.md
> +Les commandes varient selon le terminal : bash (linux ou git bash) / Windows CMD / PowerShell...
Il faudrait mieux qu'on force les étudiants à utiliser la git bash pour que ca ne parte pas dans tous les sens je pense ;)

2024-02-29 16:49 UTC, sebclrsn commented on TP1/README.md
> +- `echo`
Est-ce qu'on leur explique en une ligne à quoi ces commandes servent?

2024-02-29 16:49 UTC, sebclrsn commented on TP1/README.md
> +1. installer black et flake8 avec pip
```suggestion
1. installer ``black`` et ``flake8`` avec ``pip``
```

2024-02-29 16:49 UTC, sebclrsn commented on TP1/README.md
> +Comme exemple, vous pourrez copier-coller un morcreau de n'importe quelle documentation de python dans un fichier texte.
```suggestion
Comme exemple, vous pourrez copier-coller un morceau de n'importe quelle documentation de python dans un fichier texte.
```

2024-02-29 16:49 UTC, sebclrsn commented on TP1/README.md
> +Le programme devra compter le nombre de fois que le mot "python" est écrit dans le fichier et l'afficher à l'écran. En cas d'échec de lecture du fichier saisi par l'utilisateur, le programme demande
Est-ce qu'on le fait case-sensitive ou pas?

2024-02-29 19:11 UTC, sebclrsn commented
On ajouterait pas un petit exo sur la recursion ? 
Du style trouver les valeurs les plus lointaines dans un dictionnaire à plusieurs niveaux ?

2024-03-01 10:07 UTC, LoicRiegel commented on TP1/README.md
> +- `echo`
Ils ont un example en dessous, et sinon ce sera google ou on expliquera à l'oral

2024-03-01 10:07 UTC, LoicRiegel commented on TP1/README.md
> +Les commandes varient selon le terminal : bash (linux ou git bash) / Windows CMD / PowerShell...
oui tu as raison! J'ai adapté le texte

2024-03-01 10:10 UTC, LoicRiegel commented on TP1/README.md
> +Le programme devra compter le nombre de fois que le mot "python" est écrit dans le fichier et l'afficher à l'écran. En cas d'échec de lecture du fichier saisi par l'utilisateur, le programme demande
j'ai répondu sur MatterMost

2024-03-01 10:20 UTC, LoicRiegel commented
> On ajouterait pas un petit exo sur la recursion ? Du style trouver les valeurs les plus lointaines dans un dictionnaire à plusieurs niveaux ?

Très bonne idée! Done

2024-03-04 07:56 UTC, sebclrsn approved these changes

2024-03-04 08:08 UTC, merged