Ajout TP5
sebclrsn/TP-AOO-python-git pull request #14
Opened 2024-04-08 09:59 UTC by LoicRiegel

Ajout TP5

**J'ai commencé l'implémentation du package sur un repo à moi mais c'est en local pour l'instant. Je leur donnerai comme correction après le TP.**

Je suis content de pouvoir aborder ces notions et de leur donner un projet clean et complet en correction pour finir le cours! Même si on survole certaines choses, ils sauront à quoi ressemble un vrai projet python et sauront naviguer et comprendre les projets qu'ils peuvent voir sur GitHub

2024-04-09 14:48 UTC, sebclrsn commented on TP5/README.md
> +Nous allons voir comment créer un package python et comment créer une application CLI (Command line Interface).
Il faudrait peut-etre expliquer rapidement ce qu'est une CLI:

```markdown
Une application CLI (Command Line Interface, interface en ligne de commande) permet d'executer le code d'un projet sous forme de commandes, directement depuis le terminal. Par exemple, ``git status`` est une des commandes de l'interface en ligne de commande de ``git``.
```

2024-04-09 14:51 UTC, sebclrsn commented on TP5/README.md
> +Une manière très répandue est de créer un package python puis de le publier sur [PYPY](https://www.pypy.org/). Une fois cela fait, les utilisateurs peuvent installer notre application simplement avec
```suggestion
Une manière très répandue est de créer un package python puis de le publier sur [PyPI](https://www.pypi.org/). Une fois cela fait, les utilisateurs peuvent installer notre application simplement avec `pip install xzy-package` ou bien l’ajouter facilement en tant que dépendance à d’autres projets.
```

Une lettre peut tout changer, PyPy c'est un interpreteur Python alternatif ;)

2024-04-09 14:54 UTC, sebclrsn requested changes

2024-04-09 14:54 UTC, sebclrsn commented on TP5/README.md
> +1. Installez poetr : `pip install poetry`
```suggestion
1. Installez poetry : `pip install poetry`
```

2024-04-09 14:54 UTC, sebclrsn commented on TP5/README.md
> +**Attention, poetry fonctionne avec des environnements virtuels**. Jusqu’à maintenant, nous avons toujours travaillé dans votre environnement python global, mais cela pose problème lorsque l’on trava
```suggestion
**Attention, poetry fonctionne avec des environnements virtuels**. Jusqu’à maintenant, nous avons toujours travaillé dans votre environnement python global, mais cela pose problème lorsque l’on travaille sur plusieurs projets en même temps, car ceux-ci peuvent avoir des dépendances différentes. Par exemple, un projet pourrait avoir besoin de ``request 2.31.0`` alors qu’un second projet aurait besoin de ``requests 1.2.3``. Ces deux versions sont incompatibles, et il est impossible d’installer ``requests`` ``2.31.0`` et ``1.2.3`` en même temps dans un même environnement.  Une solution est d’utiliser deux environnements virtuels :
```

2024-04-10 12:27 UTC, LoicRiegel commented on TP5/README.md
> +Nous allons voir comment créer un package python et comment créer une application CLI (Command line Interface).
Je détaille ca dans la partie correspondante plus bas. Mais j'aie bien ta phrase, je l'ai rajouté là-bas du coup

2024-04-10 12:28 UTC, LoicRiegel commented on TP5/README.md
> +Une manière très répandue est de créer un package python puis de le publier sur [PYPY](https://www.pypy.org/). Une fois cela fait, les utilisateurs peuvent installer notre application simplement avec
Effectivement :)

2024-04-10 14:19 UTC, LoicRiegel commented
@sebclrsn j'ai fait pas mal de modifications :
- enlevé poetry, on a un pyproject.toml avec setuptools à la place
- ajouté des détails de manière générale

J'ai testé exactement les mêmes étapes, ca marche (chez moi en tout cas)

2024-04-12 12:47 UTC, sebclrsn approved these changes

2024-04-12 12:47 UTC, merged